package constants

const (
	CHARLES_CONTROL = "http://control.charles"
	CHARLES_THROTTLING_ACTIVATE = "throttling/activate"
	CHARLES_THROTTLING_DECTIVATE = "throttling/deactivate"
	CHARLES_PRESET = "?preset="
	
	THROTTLING_PRESET_56KBPS = "56+kbps+Modem"
	THROTTLING_PRESET_256KBPS = "256+kbps+ISDN%2FDSL"
	THROTTLING_PRESET_512KBPS = "512+kbps+ISDN%2FDSL"
	THROTTLING_PRESET_2MBPS = "2+Mbps+ADSL"
	THROTTLING_PRESET_8MBPS = "8+Mbps+ADSL2"
	THROTTLING_PRESET_16MBPS = "16+Mbps+ADSL2%2B"
	THROTTLING_PRESET_32MBPS_VDSL = "32+Mbps+VDSL"
	THROTTLING_PRESET_32MBPS_FIBRE = "32+Mbps+Fibre"
	THROTTLING_PRESET_100MBPS_FIBRE = "100+Mbps+Fibre"
	THROTTLING_PRESET_3G = "3G"
	THROTTLING_PRESET_4G = "4G"
)